language: python
python:
- 3.8
- 3.7
- 3.6

before_install:
- pip install twine
- pip install -U pip setuptools wheel tox-travis

install:
- pip install -r ./requirements_dev.txt

branches:
  only:
  - master

script:
- python setup.py sdist
- python setup.py bdist_wheel
- twine check dist/*
- tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_existing: true
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.project_slug }}
    tags: true
