name: Deploy

on:
  push:
    tags:
      - "v*.[0-9]"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      {% if cookiecutter.use_webpack == 'y' -%}
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      {%- endif %}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
      {% if cookiecutter.use_webpack == 'y' -%}
      - name: Install NPM dependencies
        run: npm ci
      - name: Run webpack
        run: npx webpack --mode=production
      {%- endif %}
      - name: Build and publish
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${% raw %}{{ secrets.PYPI_PASSWORD }}{% endraw %}
        run: |
          python setup.py sdist bdist_wheel
          twine check dist/*
          twine upload dist/*
