name: Tests

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    name: Python ${% raw %}{{ matrix.python-version }}{% endraw %}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.8
          - 3.9
          - "3.10"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${% raw %}{{ matrix.python-version }}{% endraw %}
        uses: actions/setup-python@v2
        with:
          python-version: ${% raw %}{{ matrix.python-version }}{% endraw %}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools tox
      - name: Run tox targets for ${% raw %}{{ matrix.python-version }}{% endraw %}
        run: |
          ENV_PREFIX=$(tr -C -d "0-9" <<< "${% raw %}{{ matrix.python-version }}{% endraw %}")
          TOXENV=$(tox --listenvs | grep "^py$ENV_PREFIX" | tr '\n' ',')
          tox -e "$TOXENV"
